### ISSUE TITLE
Tests not passing

### ISSUE THREAD

**Issue by hseeberger** [streambed/streambed-rs#14]
Without any code changes (commit e08bf43) the tests are not passing on my machine (macOS 12.5, Rust 1.63.0):

```
running 5 tests
test crypto::tests::encrypt_decrypt ... ok
test confidant::tests::test_set_get_secret ... FAILED
test logged::tests::test_produce_consume ... ok
test logged::tests::test_consume_with_idle ... ok
test logged::tests::test_consume_wait_for_append ... ok

failures:

---- confidant::tests::test_set_get_secret stdout ----
Writing to /var/folders/_9/6jpmdl_91cbgk_gk5f_0b9mw0000gn/T/test_set_get_secret
thread 'confidant::tests::test_set_get_secret' panicked at 'assertion failed: ss.create_secret(\"some.secret\", data.clone()).await.is_err()', src/confidant/mod.rs:220:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    confidant::tests::test_set_get_secret
```

**Comment by hseeberger** [comment]
Might be caused by my `umask 0077`. But the tests nevertheless should not fail ;-)

**Comment by huntc** [comment]
Weird that the test is working for me and on CI. I will investigate.

**Comment by huntc** [comment]
Ah - your environment must be a bit more secure than the default and not allowing group or world permissions on that temp dir. Fixed in the PR.

**Comment by hseeberger** [comment]
Yes, as I wrote my umask is set to 0077 ;-)

**Comment by huntc** [comment]
> Yes, as I wrote my umask is set to 0077 ;-)

Sorry, missed that. All should now be well.
