### ISSUE TITLE
FileLog::new should take an Into<PathBuf>

### ISSUE THREAD

**Issue by hseeberger** [streambed/streambed-rs#16]
This would allow for something like `FileLog::new("foo")`.

Happy to come up with a PR ...

**Comment by huntc** [comment]
Thanks. I wonder if you’d need it though? Paths are hardly ever literals.

**Comment by hseeberger** [comment]
Not necessarily literals, but what about strings, e.g. from config files?

**Comment by huntc** [comment]
Just checked in std - the pattern appears to be using`[AsRef](https://doc.rust-lang.org/std/convert/trait.AsRef.html)<[Path](https://doc.rust-lang.org/std/path/struct.Path.html)>, but here in particular, we're looking to own the path. When looking to own something, the style is to avoid passing in a ref...

Also, when reading in from config files, you'll end up with strings, not literals.

**Comment by hseeberger** [comment]
As I wrote, `Into<PathBuf>` also works for `String`s, because there's an `From<String>` impl for `PathBuf`.

**Comment by huntc** [comment]
> As I wrote, `Into<PathBuf>` also works for `String`s, because there's an `From<String>` impl for `PathBuf`.

I really should read what you write more thoroughly! ;-)

**Comment by hseeberger** [comment]
> I really should read what you write more thoroughly! ;-)

LOL

**Comment by hseeberger** [comment]
Fix in https://github.com/streambed/streambed-rs/pull/19
